In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('main_4.csv')

In [4]:
tmp1 = df.head(len(df) // 2)
tmp2 = df.tail(len(df)// 2)

In [5]:
tmp1

,Unnamed: 0.1,Unnamed: 0,Released,English title,TMDB_id,Genre,Score,Popularity,Overview,Or_lan,Casts
0,0,0,1990-01-12,Downtown,60778,Action Comedy,5.649,7.700,Officer Alex Kearney patrols an upscale neighb...,en,"{'cast': [{'adult': False, 'gender': 2, 'id': ..."
1,1,1,1990-01-12,Internal Affairs,11060,Crime Drama,6.300,16.669,Keen young Raymold Avila joins the Internal Af...,en,"{'cast': [{'adult': False, 'gender': 2, 'id': ..."
2,2,2,1990-01-12,Leatherface: The Texas Chainsaw Massacre III,25018,Horror Thriller,5.265,41.537,Two college students driving coast to coast ar...,en,"{'cast': [{'adult': False, 'gender': 1, 'id': ..."
3,3,3,1990-01-12,Ski Patrol,22585,Comedy Action,4.861,9.159,Pops isn't worried about the renewal of the le...,en,"{'cast': [{'adult': False, 'gender': 2, 'id': ..."
4,4,4,1990-01-19,Everybody Wins,41816,Crime,3.800,10.041,A seemingly good Samaritan hires a private det...,en,"{'cast': [{'adult': False, 'gender': 1, 'id': ..."
...,...,...,...,...,...,...,...,...,...,...,...
967,967,967,1996-06-21,Eraser,9268,Action Drama Mystery Thriller,6.047,27.263,U.S. Marshall John Kruger erases the identitie...,en,"{'cast': [{'adult': False, 'gender': 2, 'id': ..."
968,968,968,1996-06-21,The Hunchback of Notre Dame,10545,Drama Animation Family,7.108,63.193,"At the urging of his gargoyle pals, Quasimodo ...",en,"{'cast': [{'adult': False, 'gender': 2, 'id': ..."
969,969,969,1996-06-21,Lone Star,26748,Drama Mystery Romance,7.000,12.476,When the skeleton of his murdered predecessor ...,en,"{'cast': [{'adult': False, 'gender': 2, 'id': ..."
970,970,970,1996-06-28,The Nutty Professor,9327,Fantasy Comedy Romance Science Fiction,5.630,40.988,"Eddie Murphy stars as shy Dr. Sherman Klump, a...",en,"{'cast': [{'adult': False, 'gender': 2, 'id': ..."
971,971,971,1996-06-28,Striptease,9879,Comedy Crime Drama,5.541,19.280,"Bounced from her job, Erin Grant needs money i...",en,"{'cast': [{'adult': False, 'gender': 1, 'id': ..."

In [6]:
tmp1.to_csv('main_4.csv')

In [7]:
tmp2.to_csv('main_11.csv')